services:
  mysql:
    image: mysql:8.0
    container_name: attacker_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: KEYDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: ./infrac
    container_name: attacker_api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://admin:admin123@mysql:3306/KEYDB
    ports:
      - "8000:8000"
    volumes:
      - ./infrac:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=3)"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    build: ./frontend
    container_name: attacker_frontend
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      
  encrypt-tool:
    build: ./Encrypt-tool
    image: dangwminh/image-manager:latest  
    container_name: image_manager
    profiles:
      - encrypt
    restart: "no"
    volumes:
      - ./sandbox:/app/sandbox
      - ./.machine_id:/app/.machine_id


volumes:
  mysql_data:
  
